### ISSUE TITLE
New data type names in tarantool

### ISSUE THREAD

**Issue by smenshikh** [tarantool/tarantool-perl#22]
In tarantool 1.7.3 (or may be some earlier) new data types introduced (instead of old): string, unsigned

**Comment by sexyhamster** [comment]
In 1.6 was added data type Any (*)
Current version fails to establish connection with error

`EV: error in callback (ignoring): unknown field type: * at /usr/lib64/perl5/vendor_perl/DR/Tarantool/MsgPack/LLClient.pm line 189`

Tarantool 
`box.space[281]:select{}
---
- - [272, 1, '_schema', 'memtx', 0, {}, [{'type': 'str', 'name': 'key'}]]
  - [280, 1, '_space', 'memtx', 0, {}, [{'name': 'id', 'type': 'num'}, {'name': 'owner',
        'type': 'num'}, {'name': 'name', 'type': 'str'}, {'name': 'engine', 'type': 'str'},
      {'name': 'field_count', 'type': 'num'}, {'name': 'flags', 'type': 'str'}, {
        'name': 'format', 'type': '*'}]]
  - [281, 1, '_vspace', 'sysview', 0, {}, [{'name': 'id', 'type': 'num'}, {'name': 'owner',
        'type': 'num'}, {'name': 'name', 'type': 'str'}, {'name': 'engine', 'type': 'str'},
      {'name': 'field_count', 'type': 'num'}, {'name': 'flags', 'type': 'str'}, {
        'name': 'format', 'type': '*'}]]
  - [288, 1, '_index', 'memtx', 0, {}, [{'name': 'id', 'type': 'num'}, {'name': 'iid',
        'type': 'num'}, {'name': 'name', 'type': 'str'}, {'name': 'type', 'type': 'str'},
      {'name': 'opts', 'type': 'array'}, {'name': 'parts', 'type': 'array'}]]
  - [289, 1, '_vindex', 'sysview', 0, {}, [{'name': 'id', 'type': 'num'}, {'name': 'iid',
        'type': 'num'}, {'name': 'name', 'type': 'str'}, {'name': 'type', 'type': 'str'},
      {'name': 'opts', 'type': 'array'}, {'name': 'parts', 'type': 'array'}]]
  - [296, 1, '_func', 'memtx', 0, {}, [{'name': 'id', 'type': 'num'}, {'name': 'owner',
        'type': 'num'}, {'name': 'name', 'type': 'str'}, {'name': 'setuid', 'type': 'num'}]]
  - [297, 1, '_vfunc', 'sysview', 0, {}, [{'name': 'id', 'type': 'num'}, {'name': 'owner',
        'type': 'num'}, {'name': 'name', 'type': 'str'}, {'name': 'setuid', 'type': 'num'}]]
  - [304, 1, '_user', 'memtx', 0, {}, [{'name': 'id', 'type': 'num'}, {'name': 'owner',
        'type': 'num'}, {'name': 'name', 'type': 'str'}, {'name': 'type', 'type': 'str'},
      {'name': 'auth', 'type': '*'}]]
  - [305, 1, '_vuser', 'sysview', 0, {}, [{'name': 'id', 'type': 'num'}, {'name': 'owner',
        'type': 'num'}, {'name': 'name', 'type': 'str'}, {'name': 'type', 'type': 'str'},
      {'name': 'auth', 'type': '*'}]]
  - [312, 1, '_priv', 'memtx', 0, {}, [{'name': 'grantor', 'type': 'num'}, {'name': 'grantee',
        'type': 'num'}, {'name': 'object_type', 'type': 'str'}, {'name': 'object_id',
        'type': 'num'}, {'name': 'privilege', 'type': 'num'}]]
  - [313, 1, '_vpriv', 'sysview', 0, {}, [{'name': 'grantor', 'type': 'num'}, {'name': 'grantee',
        'type': 'num'}, {'name': 'object_type', 'type': 'str'}, {'name': 'object_id',
        'type': 'num'}, {'name': 'privilege', 'type': 'num'}]]
  - [320, 1, '_cluster', 'memtx', 0, {}, [{'name': 'id', 'type': 'num'}, {'name': 'uuid',
        'type': 'str'}]]
  - [512, 1, '_queue', 'memtx', 0, {}, [{'name': 'tube_name', 'type': 'str'}, {'name': 'tube_id',
        'type': 'num'}, {'name': 'space_name', 'type': 'str'}, {'name': 'tube_type',
        'type': 'str'}, {'name': 'opts', 'type': '*'}]]
  - [513, 1, '_queue_consumers', 'memtx', 0, {'temporary': true}, [{'name': 'session_id',
        'type': 'num'}, {'name': 'fiber_id', 'type': 'num'}, {'name': 'tube_id', 'type': 'num'},
      {'name': 'event_time', 'type': 'num'}, {'name': 'fiber_time', 'type': 'num'}]]
  - [514, 1, '_queue_taken', 'memtx', 0, {'temporary': true}, [{'name': 'session_id',
        'type': 'num'}, {'name': 'tube_id', 'type': 'num'}, {'name': 'task_id', 'type': 'num'},
      {'name': 'taken_time', 'type': 'num'}]]
  - [515, 1, 'bernadette', 'memtx', 0, {'temporary': false}, [{'name': 'task_id',
        'type': 'num'}, {'name': 'status', 'type': 'str'}, {'name': 'next_event',
        'type': 'num'}, {'name': 'ttl', 'type': 'num'}, {'name': 'ttr', 'type': 'num'},
      {'name': 'pri', 'type': 'num'}, {'name': 'created', 'type': 'num'}, {'name': 'data',
        'type': '*'}]]
  - [516, 1, 'relations', 'memtx', 0, {}, []]
  - [517, 1, 'queue_stat', 'memtx', 0, {}, []]`

**Comment by Awety** [comment]
Fixed in branch **origin/issue-22-new-data-types**. Merged into master.

```sh
$ git merge origin/issue-22-new-data-types --no-ff
Merge made by the 'recursive' strategy.
 lib/DR/Tarantool/MsgPack/AsyncClient.pm |  4 ++--
 lib/DR/Tarantool/Spaces.pm              | 12 ++++++------
 2 files changed, 8 insertions(+), 8 deletions(-)
```

Your, @smenshikh , problem is reproduced with the following tarantool configuration:
```sh
tarantool> box.schema.space.create('tester')
tarantool> box.space.tester:create_index('primary', {
 type = 'hash',
parts = {1, 'number',2,'scalar',3,'unsigned'}
})
```
Your, @sexyhamster , problem is reproduced with the following tarantool configuration:

```sh
tarantool> box.schema.space.create('tester4', {
id = 778,
format = {
[1] = {['name'] = 'field1'},
[2] = {['type'] = '*'},
}
})
tarantool> box.space.tester4:create_index('primary', {
 type = 'hash',
parts = {1, 'number'}
})
```
Now it's ok for both.
