### ISSUE TITLE
Problem with an example for 1.7

### ISSUE THREAD

**Issue by lenkis** [tarantool/tarantool-perl#23]
Installed `tarantool-perl` module from GitHub.

Started Tarantool 1.7 Docker image and attached to the instance as said here: https://tarantool.org/en/doc/1.7/book/getting_started/using_docker.html#attaching-to-tarantool

Adjusted example from https://tarantool.org/en/doc/1.7/book/connectors/index.html#perl as follows:
```
#!/usr/bin/env perl

use AnyEvent;
use Data::Dumper;
use DR::Tarantool;
use DR::Tarantool::MsgPack::AsyncClient;

my $host = '127.0.0.1';
my $port = '3301';

my $cv = AnyEvent->condvar();
DR::Tarantool::MsgPack::AsyncClient->connect(
    host => $host,
    port => $port,
     sub {
         shift->select(
             'tester', 
             'primary',
             [2],
             sub { print Dumper $_[1]->raw; $cv->send }
         );
     }
    );
# ... your code here
$cv->recv();
```

Got this error:
```
unknown field type: UNSIGNED at /Users/alpha6/perl5/perlbrew/perls/perl-5.20.3/lib/site_perl/5.20.3/darwin-2level/DR/Tarantool/MsgPack/LLClient.pm line 190.
```

Probably the example is outdated, or there might be a bug in the module. Please check with Tarantool 1.7. Have no problems with 1.6.

P.S. Got a warning when building the module:
```
perl ./Makefile.PL
Checking if your kit is complete...
Warning: the following files are missing in your kit:
  msgpack.o
  Tarantool.bs
  Tarantool.c
  Tarantool.o
Please inform the author.
```

**Comment by Awety** [comment]
Elena, thanks for giving the feedback.

It seems like your problem relates to #22. I see the case becomes popular, so I'm going to fix it as soon as possible.

P.S. The warning is also known and recognized to be harmless :) So, you could ignore it so far.
