### ISSUE TITLE
DR::Tarantool::RealSyncClient endless loop

### ISSUE THREAD

**Issue by fsitedev** [tarantool/tarantool-perl#3]
tarantool: 1.6.7-463-gfc14541
perl: 5.14

This simple test hangs out the client process with 100% cpu utilization
>perl -MDR::Tarantool::RealSyncClient -e 'DR::Tarantool::RealSyncClient->connect(host => "127.0.0.1", port => 3301)->ping' 

strace by the client process pid
```
read(3, "", 1869575162)                 = 0
read(3, "", 1869575162)                 = 0
read(3, "", 1869575162)                 = 0
read(3, "", 1869575162)                 = 0
read(3, "", 1869575162)                 = 0
read(3, "", 1869575162)                 = 0
read(3, "", 1869575162)                 = 0
read(3, "", 1869575162)                 = 0
```

tarantool log
```
2015-12-11 18:08:38.275 [32048] iproto xrow.cc:50 E> ER_INVALID_MSGPACK: Invalid MsgPack - packet header
```

**Comment by Awety** [comment]
At least, I found where problem was. Here: DR::Tarantool::LLSyncClient.pm
```perl
while(12 + $blen > length $pkt) {
      no warnings; # closed socket
      my $rl = sysread $self->{fh},
          $pkt, 12 + $blen - length $pkt, length $pkt;
      goto SOCKET_ERROR unless defined $rl;
}
```
First read of 12 bytes (piece of code before) should (as was assumed) be a packed length of the following message, but here Tarantool returns such a message instead (I tried to read first 120 bytes):
`
Tarantool 1.6.7 (Binary) c9b0e476-3d6d-4f50-817d-fc70fc8f993b
2x7q6WCJA1NQZ3g+BkU9mB1eFtCDXsxFOEPu1BrZ7e4=
`
however it works perfectly with tarantool 1.5, which returns something that really doesn't look like this message. Seems like the problem here in logic of how the try to read messages from tarantool. I don't know if Tarantool 1.6 responds the same way here as the older version did.

**Comment by rtsisyk** [comment]
Tarantool 1.6 always responds with text greeting (128 bytes).

**Comment by Awety** [comment]
Yes, I've just read that in doc :)

**Comment by rtsisyk** [comment]
http://tarantool.org/doc/dev_guide/box-protocol.html
I can help you with the 1.6 protocol. 
What is about async client? Does it work?

**Comment by Awety** [comment]
Tried to test this way:
```perl
use strict;
use warnings;

use Data::Dumper;
use AnyEvent;
use DR::Tarantool::AsyncClient;

my $cv = AnyEvent->condvar();

DR::Tarantool::AsyncClient->connect(
    host => "my_tarantool_ip",
    port => 3301,
    cb => sub{
        warn 1;
        shift->ping(
            sub { warn Dumper \@_; $cv->send() }
        );
    }
);

$cv->recv();
```
And got:
`
1 at test.pl line 17.
$VAR1 = [
          'fatal',
          undef,
          'Socket error: Server closed connection'
        ];
`
Tarantool says:
`
2015-12-22 12:58:34.428 [5469] iproto xrow.cc:50 E> ER_INVALID_MSGPACK: Invalid MsgPack - packet header
`

So, it looks like this one also doesn't work.

**Comment by Awety** [comment]
Ok, thanks to Tarantool developers team, I got the point.
Here in the example above we try to use incorrect libraries (they are for 1.5 version) to connect to Tarantool 1.6, which has completely another protocol.
The correct way of working with 1.6 version is the following:
```perl
use strict;
use warnings;

BEGIN {
    unshift @INC, '/home/awety/tarantool-perl/blib/lib/';
}
use Data::Dumper;
use AnyEvent;
use DR::Tarantool::MsgPack::SyncClient;

DR::Tarantool::MsgPack::SyncClient->connect(host => "127.0.0.1", port => 3301)->ping
```
So, tarantool 1.6 compatible libs are stored in the MsgPack repo's directory.

**Comment by fsitedev** [comment]
Issue was about DR::Tarantool::**RealSyncClient** library.

DR::Tarantool::MsgPack::SyncClient is just a simplier wrapper for DR::Tarantool::MsgPack::AsyncClient and has a huge overhead in simple synchronous applications.

**Comment by Awety** [comment]
Yes, it's true, but DR::Tarantool::RealSyncClient doesn't support Tarantool 1.6. In details, it waits for completely different response message format from tarantool, which is correct for 1.5 version only.
